name: Deploy Artifacty
on:
  push:
    branches:
      - "master"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: code checkout
        uses: actions/checkout@v2

      - name: install the gcloud cli
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          install_components: "gke-gcloud-auth-plugin"
          export_default_credentials: true

      - name: build and push the docker image
        env:
          GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/terraform-images/backend-terraform:${{ github.sha }} .
          docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/terraform-images/backend-terraform:${{ github.sha }}
  argo:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
        name: modify values.yaml
        with:
          repository: tariq-ventura/argoCD
          token: ${{ secrets.TOKEN }}
      - name: write
        run: |
          git config user.email tariqventura@gmail.com
          git config user.name tariq-ventura
          sed -i 's|tag:.*|tag: '${{ github.sha }}'|' app/values.yaml 
          git add .
          git commit -m "update docker tag"
          git push

